{{- if .Values.agent.enabled }}
apiVersion: cloudwatch.aws.amazon.com/v1alpha1
kind: AmazonCloudWatchAgent
metadata:
  name: {{ template "cloudwatch-agent.name" . }}-windows
  namespace: {{ .Release.Namespace }}
spec:
  securityContext:
    windowsOptions:
      hostProcess: true
      runAsUserName: "NT AUTHORITY\\System"
  hostNetwork: true
  image: {{ template "cloudwatch-agent-windows.image" . }}
  command: ["%CONTAINER_SANDBOX_MOUNT_POINT%/Program Files/Amazon/AmazonCloudWatchAgent/start-amazon-cloudwatch-agent.exe"]
  mode: daemonset
  serviceAccount: {{ template "cloudwatch-agent.serviceAccountName" . }}
  nodeSelector:
    kubernetes.io/os: windows
  {{- if .Values.agent.config }}
  config: {{ .Values.agent.config | toJson | quote }}
  {{- else }}
  config: {{ .Values.agent.defaultConfig | toJson | quote }}
  {{- end }}
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: HOST_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: K8S_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: RUN_AS_HOST_PROCESS_CONTAINER
    value: "True"
{{- end }}