# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: PR Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main*
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install make
        if: matrix.family == 'windows' && steps.cached_binaries.outputs.cache-hit != 'true' && needs.changes.outputs.build == 'true'
        run: choco install make

      - name: Unit Test
        if:  steps.cached_binaries.outputs.cache-hit != 'true' && needs.changes.outputs.build == 'true'
        run: make test

      - name: Upload coverage to Codecov
        if: steps.cached_binaries.outputs.cache-hit != 'true' && needs.changes.outputs.build == 'true'
        uses: codecov/codecov-action@v3
        with:
          verbose: true